- filename: DBLP.bib
  search_type: FEED
  source_name: Journal of Information Technology
  source_url: ''
  search_parameters: 
    - endpoint: dblp
      params: SCOPE venue_key='journals/jitech' AND journal_abbreviated='J. Inf. Technol.'
  comment: ''