- filename: DBLP.bib
  search_type: FEED
  source_name: Journal of Information Technology
  source_url: ''
  search_parameters:
  - endpoint: dblp
    params: SCOPE venue_key='journals/jitech' AND journal_abbreviated='J. Inf. Technol.'
  last_sync: null
  comment: ''
- filename: CROSSREF.bib
  search_type: FEED
  source_name: CROSSREF
  source_url: CROSSREF.bib
  search_parameters:
  - endpoint: crossref
    params: SCOPE journal_issn='1466-4437'
  last_sync: null
  comment: ''
- filename: pdfs.bib
  search_type: FEED
  source_name: JIT
  source_url: pdfs
  search_parameters:
  - endpoint: pdfs_directory
    params: SCOPE path='pdfs' WITH journal='Journal of Information Technology' AND sub_dir_pattern='volume_number'
  comment: NA
