name: Run colrev update

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 * * 3'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      - run: |
          pip install git+https://github.com/CoLRev-Environment/colrev.git#egg=colrev
      - name: Set branch name
        run: echo "BRANCH_NAME=colrev-update-$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      - name: Setup git config and branch
        run: |
          git config user.name "CoLRev update"
          git config user.email "actions@users.noreply.github.com"
          git config --global url.https://github.com/.insteadOf git://github.com/
          git checkout -b ${{ env.BRANCH_NAME }}
      - name: Run CoLRev update
        run: |
          colrev search -f
          colrev load
          colrev prep
          colrev prep --polish
          colrev prescreen
          colrev pdfs
          colrev screen
          git push --set-upstream origin ${{ env.BRANCH_NAME }}
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ env.BRANCH_NAME }}"
          destination_branch: "main"
          pr_title: "Pull colrev search updates"
          pr_body: |
            *CoLRev updates*

            _Created by [colrev gh-action updater](https://github.com/CoLRev-Environment/colrev/tree/main/colrev/template)_
